services:
  influxdb:
    image: influxdb:2.7.4
    container_name: influxdb
    volumes:
      - influxdb-vol:/var/lib/influxdb2
    ports:
      - "8086:8086"
    restart: unless-stopped
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=admin
      - DOCKER_INFLUXDB_INIT_PASSWORD=admin123456
      - DOCKER_INFLUXDB_INIT_ORG=SolarBiz
      - DOCKER_INFLUXDB_INIT_BUCKET=solar_viz_bucket
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=a01396360b78797f0523fde24c86ee31

  grafana:
    image: grafana/grafana:10.2.1
    container_name: grafana
    depends_on:
      - influxdb
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin123456
    volumes:
      - grafana-vol:/var/lib/grafana
    ports:
      - "3000:3000"
    restart: unless-stopped

networks:
  default:
    name: solar_viz_net
    external: true

volumes:
  postgresql-vol:
  influxdb-vol:
  grafana-vol:
